name: Deploy SoundWave Web App to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Web Frontend Dependencies
        working-directory: ./web-frontend
        run: npm install

      - name: Build Web Frontend
        working-directory: ./web-frontend
        run: npx vite build

      - name: Deploy to GitHub Pages
        uses: Peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
